import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="w-full min-h-screen overflow-x-hidden relative">
                    <nav className="w-11/12 max-w-7xl mx-auto flex justify-between items-center py-4">
                        <Link href="/">
                            <img
                                src="/logo.png"
                                className="w-36 xsm:w-40 sm:w-44"
                            />
                        </Link>
                        <div className="flex items-center gap-x-1 sm:gap-x-3 xsm:border-2 border-gray-100 rounded-lg px-1.5 sm:px-3 py-1 sm:py-1.5">
                            <img
                                src="/avatar.svg"
                                className="w-8 xsm:w-7 rounded-full"
                            />
                            <p className="hidden xsm:block font-medium text-lg">
                                John Doe
                            </p>
                        </div>
                    </nav>
                    <div className="w-full h-0.5 bg-gray-100"></div>
                    {children}
                </div>
            </body>
        </html>
    );
}
